CenterForOpenScience/helm-charts

cas/templates/configmap.yaml
`id` change for Preprints LiveData (formerly ASU)
https://github.com/CenterForOpenScience/cas-overlay/pull/87
=> [CAS-92] Update Preprints: ASU -> LiveData

cas/templates/configmap.yaml
@binoculars, thanks! 🎆 
FYI, a useful API:
https://api.osf.io/v2/preprint_providers/=?filter%5Bdomain_redirect_enabled%5D=True
=> [OSF Preprints] [CAS] Add domain for MarXiv, EarthArXiv and PaleorXiv [No Ticket]

elasticsearch/README.md, elasticsearch/values.yaml
Tolerations is an array:
Replace `{}` by `[]`.
Avoid this warning:
```
helm upgrade --install elasticsearch cos/elasticsearch --namespace monitoring
2018/03/13 14:42:35 warning: cannot overwrite table with non table for tolerations (map[])
2018/03/13 14:42:35 warning: cannot overwrite table with non table for tolerations (map[])
2018/03/13 14:42:35 warning: cannot overwrite table with non table for tolerations (map[])
```
=> Fix toleration array

cas/templates/configmap.yaml
https://openscience.atlassian.net/browse/SVCS-829
Add service config for AfricArXiv Preprints
Must be merged and deployed before the CAS (PR-TBD)
=> [SVCS-829] [OSF Preprints] Add Service Config For AfricArXiv Preprints

cas/templates/configmap.yaml
https://openscience.atlassian.net/browse/SVCS-858
Add branded login support for OSF Registries.
I copied what we have for OSF Preprints and updated the following:
* Entry name: `services/registries-osf.json`
* `"id"` (the unique ID for each service): 203948234207340
* `"serviceId"` (the URL matching regex for each service): `"^https://{{ .Values.osfDomain | replace "." "\\\\." }}/login/?\\?next=https(%3A|:)(%2F|/)(%2F|/){{ .Values.osfDomain | replace "." "\\\\." }}(%2F|/)registries(%2F|/).*"`
* `"logo"`: `"https://{{ .Values.casDomain }}/images/registries-osf-logo-black.png"`
* `"registerUrl"`: `"?campaign=osf-registries"`
@binoculars Please double check this make sense. Thanks.
Need to redeploy CAS (after Helm Charts has been deployed) to load the new settings.
=> [SVCS-858] [CAS] [OSF Registries] Add branded login support for OSF Registries

osf/Chart.yaml, osf/templates/admin-deployment.yaml, osf/templates/api-deployment.yaml, osf/templates/beat-deployment.yaml, osf/templates/web-deployment.yaml
check_deploy_ready will delegate to other commands such as
checkmigrations to check if pods are ready to failover. This
will allow us to add more checks without having to change
these charts every time.
h/t @icereval for showing me where to make this change
=> Use check_deploy_ready command to check if app is ready to deploy

osf/Chart.yaml, osf/templates/migration-job.yaml
This command will be used to run both `python mangage.py migrate`
and `python manage.py sync_metrics` automatically on
staging environments.
=> Use sync_databases to run migrations and sync other DBs

cas/templates/configmap.yaml
https://openscience.atlassian.net/browse/SVCS-949
=> [SVCS-949] Add MediArxiv to CAS branded sign-in

cas/templates/configmap.yaml
https://openscience.atlassian.net/browse/SVCS-955
=> [SVCS-955] Add BodoArXiv To CAS Branded Sign-in

cas/templates/configmap.yaml
Add  EdArXiv to CAS branded sign-in.
Must be deployed before: https://github.com/CenterForOpenScience/cas-overlay/pull/149
https://openscience.atlassian.net/browse/ENG-377
=> [OSF Preprints] EdArXiv Branded Login [ENG-377]

cas/templates/configmap.yaml
Add  IndiaRxiv to CAS branded sign-in.
https://openscience.atlassian.net/browse/ENG-579
=> [OSF Preprints] IndiaRxiv Branded Login [ENG-579]

cas/templates/configmap.yaml
EdArXiv Preprints wants to use a customized domain: `edarxiv.org`.
New: https://openscience.atlassian.net/browse/ENG-597
Old: https://openscience.atlassian.net/browse/ENG-377
=> [OSF Preprints] Branded Domain For EdArXiv [ENG-597]

cas/templates/configmap.yaml
Add  BioHackrXiv to CAS branded sign-in.
https://openscience.atlassian.net/browse/ENG-1271
=> [ENG-1271] [OSF Preprints] Branded Sign-in for BioHackrXiv 

cas/templates/configmap.yaml
* PR: https://github.com/CenterForOpenScience/cas-overlay/pull/168
* Ticket: https://openscience.atlassian.net/browse/ENG-1134
* Use system environment variables when configuring `osf.database.hibernate.dialect` so that staging, test and prod servers can have different dialect. This is required by https://github.com/CenterForOpenScience/cas-overlay/pull/168.
* Updated `osf.database.driverClass` as well (to make all OSF DB settings look consistent).
* This PR blocks https://github.com/CenterForOpenScience/cas-overlay/pull/168.
* This PR can be merged without causing any effect until an ENV is added to the server OS and the server is redeployed.
=> [No Ticket] Update `cas.properties` to use SYS ENV for OSF DB dialect

cas/templates/configmap.yaml
Update CAS's default hibernate dialect for OSF database.
No effect and no need to redeploy CAS.
=> [No Ticket] Update CAS's default hibernate dialect for OSF database

cas/templates/configmap.yaml
Add  HSRxiv to CAS branded sign-in.
- Customized Domain: N / A
https://openscience.atlassian.net/browse/ENG-1415
=> [ENG-1415] [OSF Preprints] Branded Sign-in for HSRxiv

cas/templates/configmap.yaml
Update `cas.properties` for Concordia College
```xml
<xsl:when test="$idp='cord'">
<id>cord</id>
<user>
<username><xsl:value-of select="//attribute[@name='mail']/@value"/></username>
<fullname><xsl:value-of select="//attribute[@name='displayName']/@value"/></fullname>
<familyName />
<givenName />
<middleNames/>
<suffix/>
</user>
</xsl:when>
```
* Ticket: https://openscience.atlassian.net/browse/ENG-810
* CAS PR: https://github.com/CenterForOpenScience/cas-overlay/pull/178
* OSF PR: https://github.com/CenterForOpenScience/osf.io/pull/9279
=> [Supporting ENG-810] CAS settings for Institution SSO with Concordia College

cas/templates/configmap.yaml
https://openscience.atlassian.net/browse/ENG-2005
Update / fix CAS logging to debug OKState logging issue. `debug` level has been turned on for
* `io.cos`
* `org.jasig.cas`
* `org.pac4j`
* `org.springframework.web.servlet`
* `org.springframework.webflow`
Somehow `sentry` was configured but not enabled. This has been fixed.
@mfraezz Let's deploy the `staging` and `test` servers first. I will check the logs before `prod` deployment.
=> [ENG-2005] Update logging level for CAS

cas/templates/configmap.yaml
- Default values are provided so it is optional to set system ENVs
- Connection timeout is 10 sec
- Read timeout is 1 min
=> [Support ENG-2171] Add timeout setting for CAS ORCID login

osf-cas/templates/configmap.yaml
https://openscience.atlassian.net/browse/ENG-1887
The current charts (from oldCAS) seem to clear the `etc/cas` directory during deployment, while the repo `cas.properties` and `log4j2.xml` are expected to be used directly in newCAS (a new thing I introduced ...). This one difference now prevents OSF CAS from starting properly to run since it has no `cas.properties` file to use at all. This PR adds these two files (currently these are the only two) back for `staging3` deployment.
For the final version when we refactor all "jetty" to "tomcat", let's take a look and see if we can fix this design where repo files can used.
I doubt that it will work since part of "applying env vars and secrets" may be closely coupled with the charts which prevents the repo file to be correctly updated even if …
=> [ENG-1887] Fix charts for newCAS 

cas/templates/configmap.yaml
Supports [ENG-2241](https://openscience.atlassian.net/browse/ENG-2241) with [oldCAS-#195](https://github.com/CenterForOpenScience/cas-overlay/pull/195) and [OSF-#9606](https://github.com/CenterForOpenScience/osf.io/pull/9606).
Merge and build. This one does not break existing oldCAS and thus is not blocked by the two PRs above.
=> [No Ticket] Add URLs to cas.properties for institution SSO bridge / migration

osf-cas/templates/configmap.yaml
@mattclark 
Add settings for OAuth server and login throttling.
The following keys have been generated, which need to be added to the private settings.
* `OAUTH_JWT_ACCESS_TOKEN_SIGNING_KEY`
* `OAUTH_JWT_ACCESS_TOKEN_ENCRYPTION_KEY`
* `OAUTH_REGISTERED_SERVICE_SIGNING_KEY`
* `OAUTH_REGISTERED_SERVICE_ENCRYPTION_KEY`
* https://github.com/CenterForOpenScience/osf-cas/pull/23
* https://github.com/CenterForOpenScience/osf-cas/pull/20
=> newCAS settings for OAuth server and login throttling

share/Chart.yaml, share/templates/worker-deployment.yaml
the `--app` arg must go before the `worker` command in celery 5:
`celery worker --app project ...` => `celery --app project worker ...`
required for deploying https://github.com/CenterForOpenScience/SHARE/pull/788
=> update share worker invocation for celery upgrade

osf-cas/templates/configmap.yaml
https://openscience.atlassian.net/browse/ENG-3583
@mfraezz
Bump TGT expiration time to 90 days (7776000 in seconds) so that related ATs and RTs won't get deleted before their own expiration time. This is a temporary solution. See more details in the [ticket](https://openscience.atlassian.net/browse/ENG-3583).
Don't deploy on prod until staging or test is verified. Verification takes two hours.
This one doesn't solve the design limitation (for better security) of TGT deletion caused by signing out of CAS. However, this is not common during "log in with OSF".
=> [ENG-3583] Bump TGT expiration policy

osf-cas/templates/configmap.yaml
Enable the `/actuator/health` endpoint for K8s liveness probing.
For details, refer to the [CAS PR](https://github.com/CenterForOpenScience/osf-cas/pull/62)
=> [ENG-3773] Enable CAS health endpoint for K8s probing

osf-cas/templates/configmap.yaml
We happen to left out one config where defines how many CAS clients are configured. This lead to CAS mistakenly configuring an extra clients. This doesn't break CAS and but needs to be fixed. Here is how is looks like locally (`test` and `prod` don't have `osftype0`)
```
INFO [io.cos.cas.osf.web.flow.login.OsfPrincipalFromNonInteractiveCredentialsAction] - <cord>                                                                                                                                                                                                                                                      
INFO [io.cos.cas.osf.web.flow.login.OsfPrincipalFromNonInteractiveCredentialsAction] - <osftype0> …
```
=> Trim  institution CAS clients due to okstate cas-to-saml migration
